###########
# site.title

title:    'RamboSteve'
subtitle: 'CS 175: Project in AI (in Minecraft)'
baseurl: 'blog'

#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-hacker

plugins:
    - jekyll-include-cache
