###########
# site.title

title:    'RamboSteve'
subtitle: 'CS 175: Project in AI (in Minecraft)'
description: 'This site details the work put into our class for CS 175'

#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-hacker
